{{- if and .Values.bakery.enabled (.Values.bakery.serviceAccount.create | default true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bakery.serviceAccountName" . }}
  labels:
    {{- include "bakery.labels" . | nindent 4 }}
  {{- with .Values.bakery.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
