apiVersion: v2
name: bakery
description: Standalone communication integration service for external ticketing and messaging systems
type: application
version: 0.1.27
appVersion: "0.1.27"
maintainers:
  - name: Jake Briggs
keywords:
  - communications
  - ticketing
  - messaging
  - fastapi
  - integrations
home: https://github.com/rackerlabs/bakery
sources:
  - https://github.com/rackerlabs/bakery
